# Generated by Django 4.1.6 on 2023-02-17 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_authors_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_category',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='post_category',
            name='posts',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='authors',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='responds',
            old_name='posts',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='name_category',
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='responds',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.authors'),
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Post_Category',
        ),
        migrations.AddField(
            model_name='posts',
            name='name_category',
            field=models.CharField(choices=[('TNK', 'Танки'), ('HL', 'Хилы'), ('DD', 'ДД'), ('SLR', 'Торговцы'), ('GLD', 'Гильдмастеры'), ('QST', 'Квестгиверы'), ('HMR', 'Кузнецы'), ('SKR', 'Кожевники'), ('PSN', 'Зельевары'), ('WZD', 'Мастера заклинаний')], default='', max_length=5),
        ),
    ]
