# Generated by Django 4.1.6 on 2023-02-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_alter_authors_user_alter_responds_hater_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responds',
            name='text_respond',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
