# Generated by Django 4.1.6 on 2023-02-17 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_remove_post_category_categories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responds',
            old_name='user',
            new_name='hater',
        ),
    ]
