# Generated by Django 4.1.6 on 2023-02-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_rename_user_responds_hater'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='authors',
            name='subscribe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='responds',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='responds',
            name='accepted_notice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='responds',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='responds',
            name='deleted_notice',
            field=models.BooleanField(default=False),
        ),
    ]
