# Generated by Django 4.1.6 on 2023-02-23 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_authors_rate_authors_subscribe_responds_accepted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='subscribe',
            new_name='subscribers',
        ),
    ]
