# Generated by Django 4.1.6 on 2023-02-23 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0007_alter_authors_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.authors'),
        ),
        migrations.AlterField(
            model_name='responds',
            name='hater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.authors'),
        ),
        migrations.AlterField(
            model_name='responds',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.posts'),
        ),
    ]
