# Generated by Django 4.1.6 on 2023-02-23 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0008_alter_authors_user_alter_posts_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='responds',
            name='hater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.authors'),
        ),
        migrations.AlterField(
            model_name='responds',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.posts'),
        ),
        migrations.AlterField(
            model_name='responds',
            name='text_respond',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
